erDiagram
    INEGI_2010 {
        number entidad "Clave de entidad federativa"
        string nom_ent "Entidad federativa"
        number mun "Clave de municipio ó delegación"
        number nom_mun "Municipio ó delegación"
        number loc "Clave de localidad"
        number nom_loc "Localidad"
        string longitud "Longitud"
        string latitud "Latitud"
        string altitud "Altitud"
        number pobtot "Población total"
        number pobmas "Población masculina"
        number pobfem "Población femenina"
        number tviv "Total de viviendas habitadas"
        number vivpar_hab "Total de viviendas particulares habitadas"
        number vivparh_cv "Viviendas particulares habitadas"
        number prom_ocup "Promedio de ocupantes en viviendas particulares habitadas"
        number vph_pisodt "Viviendas particulares habitadas con piso de tierra"
        number vph_1dor "Viviendas particulares habitadas con un dormitori"
        number vph_2ymasd "Viviendas particulares habitadas con dos y más dormitorios"
        number vph_1cuart "Viviendas particulares habitadas con un solo cuarto"
        number vph_aguaen "Viviendas particulares habitadas que disponen de agua entubada de la red pública"
        number vph_aguafv "Viviendas particulares habitadas que no disponen de agua entubada de la red pública"
        number vph_drenaj "Viviendas particulares habitadas que disponen de drenaje"
        number vph_elect "Viviendas particulares habitadas que disponen de energía eléctrica"
        number vph_excusa "Viviendas particulares habitadas que disponen de excusado"
        number p_0a4 "Población de 0 a 4 años"
        number p_0a4_m "Población masculina de 0 a 4 años"
        number p_0a4_f "Población femenina de 0 a 4 años"
        number p_5a9 "Población de 5 a 9 años"
        number p_5a9_m "Población masculina de 5 a 9 años"
        number p_5a9_f "Población femenina de 5 a 9 años"
        number p_10a14 "Población de 10 a 14 años"
        number p_10a14_m "Población masculina de 10 a 14 años"
        number p_10a14_f "Población femenina de 10 a 14 años"
        number p_15a19 "Población de 15 a 19 años"
        number p_15a19_m "Población masculina de 15 a 19 años"
        number p_15a19_f "Población femenina de 15 a 19 años"
        number p_20a24 "Población de 20 a 24 años"
        number p_20a24_m "Población masculina de 20 a 24 años"
        number p_20a24_f "Población femenina de 20 a 24 años"
        number p_25a29 "Población de 25 a 29 años"
        number p_25a29_m "Población masculina de 25 a 29 años"
        number p_25a29_f "Población femenina de 25 a 29 años"
        number p_30a34 "Población de 30 a 34 años"
        number p_30a34_m "Población masculina de 30 a 34 años"
        number p_30a34_f "Población femenina de 30 a 34 años"
        number p_35a39 "Población de 35 a 39 años"
        number p_35a39_m "Población masculina de 35 a 39 años"
        number p_35a39_f "Población femenina de 35 a 39 años"
        number p_40a44 "Población de 40 a 44 años"
        number p_40a44_m "Población masculina de 40 a 44 años"
        number p_40a44_f "Población femenina de 40 a 44 años"
        number p_45a49 "Población de 45 a 49 años"
        number p_45a49_m "Población masculina de 45 a 49 años"
        number p_45a49_f "Población femenina de 45 a 49 años"
        number p_50a54 "Población de 50 a 54 años"
        number p_50a54_m "Población masculina de 50 a 54 años"
        number p_50a54_f "Población femenina de 50 a 54 años"
        number p_55a59 "Población de 55 a 59 años"
        number p_55a59_m "Población masculina de 55 a 59 años"
        number p_55a59_f "Población femenina de 55 a 59 años"
        number p_60a64 "Población de 60 a 64 años"
        number p_60a64_m "Población masculina de 60 a 64 años"
        number p_60a64_f "Población femenina de 60 a 64 años"
        number p_65a69 "Población de 65 a 69 años"
        number p_65a69_m "Población masculina de 65 a 69 años"
        number p_65a69_f "Población femenina de 65 a 69 años"
        number p_70a74 "Población de 70 a 74 años"
        number p_70a74_m "Población masculina de 70 a 74 años"
        number p_70a74_f "Población femenina de 70 a 74 años"
        number p_75a79 "Población de 75 a 79 años"
        number p_75a79_m "Población masculina de 75 a 79 años"
        number p_75a79_f "Población femenina de 75 a 79 años"
        number p_80a84 "Población de 80 a 84 años"
        number p_80a84_m "Población masculina de 80 a 84 años"
        number p_80a84_f "Población femenina de 80 a 84 años"
        number p_85ymas "Población de 85 años y más"
        number p_85ymasm "Población masculina de 85 años y más"
        number p_85ymasf "Población femenina de 85 años y más"
        number p_5ymas "Población de 5 años y más"
        number p_5ymasm "Población masculina de 5 años y más"
        number p_5ymasf "Población femenina de 5 años y más"
        number p_12ymas "Población de 12 años y más"
        number p_12ymasm "Población masculina de 12 años y más"
        number p_12ymasf "Población femenina de 12 años y más"
        number p_15ymas "Población de 15 años y más"
        number p_15ymasm "Población masculina de 15 años y más"
        number p_15ymasf "Población femenina de 15 años y más"
        number p_18ymas "Población de 18 años y más"
        number p_18ymasm "Población masculina de 18 años y más"
        number p_18ymasf "Población femenina de 18 años y más"
        number p_60ymas "Población de 60 años y más"
        number p_60ymasm "Población masculina de 60 años y más"
        number p_60ymasf "Población femenina de 60 años y más"
        number rel_h_m "Relación hombres-mujeres"
        number edad_med "Edad mediana de la población"
        number p5_mas_c "Población de 5 años y más que es católica"
        number p5_mas_pro "Población de 5 años y más que es protestante o evangélica"
        number p5_mas_o_r "Población de 5 años y más con otras religiones"
        number p5_mas_s_r "Población de 5 años y más sin religión"
        number p3ymas_esc "Población de 3 años y más que asiste a la escuela"
        number p3ymasescm "Población masculina de 3 años y más que asiste a la escuela"
        number p3ymasescf "Población femenina de 3 años y más que asiste a la escuela"
        number p6a11_esc "Población de 6 a 11 años que asiste a la escuela"
        number p6a11escm "Población masculina de 6 a 11 años que asiste a la escuela"
        number p6a11escf "Población femenina de 6 a 11 años que asiste a la escuela"
        number p12a14esc "Población de 12 a 14 años que asiste a la escuela"
        number p12a14escm "Población masculina de 12 a 14 años que asiste a la escuela"
        number p12a14escf "Población femenina de 12 a 14 años que asiste a la escuela"
        number p15a17esc "Población de 15 a 17 años que asiste a la escuela"
        number p18a24esc "Población de 18 a 24 años que asiste a la escuela"
        number p15ymas_an "Población de 15 años y más analfabeta"
        number p15ymasanm "Población masculina de 15 años y más analfabeta"
        number p15ymasanf "Población femenina de 15 años y más analfabeta"
        number p15ymasep_i "Población de 15 años y más con primaria incompleta"
        number p15ymasepi_m "Población masculina de 15 años y más con primaria incompleta"
        number p15ymasepi_f "Población femenina de 15 años y más con primaria incompleta"
        number p15ymasep_c "Población de 15 años y más con primaria completa"
        number p15ymasepc_m "Población masculina de 15 años y más con primaria completa"
        number p15ymasepc_f "Población femenina de 15 años y más con primaria completa"
        number p15ymases_i "Población de 15 años y más con secundaria incompleta"
        number p15ymasesi_m "Población masculina de 15 años y más con secundaria incompleta"
        number p15ymasesi_f "Población femenina de 15 años y más con secundaria incompleta"
        number p15ymases_c "Población de 15 años y más con secundaria completa"
        number p15ymasesc_m "Población masculina de 15 años y más con secundaria completa"
        number p15ymasesc_f "Población femenina de 15 años y más con secundaria completa"
        number p15ymasm_i "Población de 15 años y más con educación media superior incompleta"
        number p15ymasmi_m "Población masculina de 15 años y más con educación media superior incompleta"
        number p15ymasmi_f "Población femenina de 15 años y más con educación media superior incompleta"
        number p15ymasm_c "Población de 15 años y más con educación media superior completa"
        number p15ymasmc_m "Población masculina de 15 años y más con educación media superior completa"
        number p15ymasmc_f "Población femenina de 15 años y más con educación media superior completa"
        number p18ymas_i "Población de 18 años y más con educación superior incompleta"
        number p18ymasi_m "Población masculina de 18 años y más con educación superior incompleta"
        number p18ymasi_f "Población femenina de 18 años y más con educación superior incompleta"
        number p18ymas_c "Población de 18 años y más con educación superior completa"
        number p18ymasc_m "Población masculina de 18 años y más con educación superior completa"
        number p18ymasc_f "Población femenina de 18 años y más con educación superior completa"
        number graproes "Grado promedio de escolaridad de la población de 15 años y más"
        number graproes_m "Grado promedio de escolaridad de la población masculina de 15 años y más"
        number graproes_f "Grado promedio de escolaridad de la población femenina de 15 años y más"
        number pea "Población económicamente activa"
        number pe_mas "Población masculina económicamente activa"
        number pe_fem "Población femenina económicamente activa"
        number pei "Población económicamente inactiva"
        number pei_mas "Población masculina económicamente inactiva"
        number pei_fem "Población femenina económicamente inactiva"
        number ocupada "Población ocupada"
        number desocup "Población desocupada"
        number t_ocup_s1 "Población ocupada en el sector primario"
        number t_ocup_s2 "Población ocupada en el sector secundario"
        number t_ocup_s3 "Población ocupada en el sector terciario"
        number p_3ymhli "Población de 5 años y más hablante de lengua indígena"
        number p3hlinhe "Población de 5 años y más hablante de lengua indígena y no habla español"
        number pcon_disc "Población con discapacidad"
        number pcdisc_mot "Población con discapacidad para caminar o moverse"
        number pcdisc_vis "Población con discapacidad para ver"
        number pcdisc_aud "Población con discapacidad para escuchar"
        number pcdisc_len "Población con discapacidad para hablar o comunicarse"
        number pcdisc_aut "Población con discapacidad para atender el cuidado personal"
        number pcdisc_men "Población con discapacidad para poner atención o aprender"
        number pob_nac_e "Población nacida en la entidad"
        number pob_nac_oe "Población nacida en otra entidad"
        number p_5ymas_re "Población de 5 años y más que reside en otra entidad o país"
        number hogares "Hogares censales"
        number pob_hog "Población en hogares censales"
        number hog_jef_m "Hogares con jefatura masculina"
        number hog_jef_f "Hogares con jefatura femenina"
        number pob_hog_m "Población en hogares con jefatura masculina"
        number pob_hog_f "Población en hogares con jefatura femenina"
        number vph_radio "Viviendas particulares habitadas que disponen de radio"
        number vph_tv "Viviendas particulares habitadas que disponen de televisor"
        number vph_refri "Viviendas particulares habitadas que disponen de refrigerador"
        number vph_lavad "Viviendas particulares habitadas que disponen de lavadora"
        number vph_licua "Viviendas particulares habitadas que disponen de licuadora"
        number vph_hmicr "Viviendas particulares habitadas que disponen de horno de microondas"
        number vph_estuf "Viviendas particulares habitadas que disponen de estufa"
        number vph_tosta "Viviendas particulares habitadas que disponen de tostador de pan"
        number vph_vidgr "Viviendas particulares habitadas que disponen de videograbadora"
        number vph_dvd "Viviendas particulares habitadas que disponen de reproductor de dvd"
        number vph_tvpla "Viviendas particulares habitadas que disponen de televisor de pantalla plana"
        number vph_tvpaga "Viviendas particulares habitadas que disponen de servicio de televisión de paga"
        number vph_pelis "Viviendas particulares habitadas que disponen de servicio de peliculas por internet"
        number vph_juego "Viviendas particulares habitadas que disponen de consola de videojuegos"
        number vph_auto "Viviendas particulares habitadas que disponen de automóvil o camioneta"
        number vph_moto "Viviendas particulares habitadas que disponen de motocicleta o motoneta"
        number vph_bici "Viviendas particulares habitadas que disponen de bicicleta"
        number vph_pc "Viviendas particulares habitadas que disponen de computadora"
        number vph_telef "Viviendas particulares habitadas que disponen de línea telefónica fija"
        number vph_cel "Viviendas particulares habitadas que disponen de teléfono celular"
        number vph_inter "Viviendas particulares habitadas que disponen de internet"
        number tam_loc "Tamaño de localidad"

    }
    INEGI_2020 {
        string name
    }
    CONEVAL {
        string name
    }
    Movilidad {
        string name
    }
    DENUE {
        number Codigo 
        number Sector
        number Subsector
        number Rama
        number Subrama
        string Titulo
        string Descripcion
    }
    COVID19 {
        string name
    }
    IRAG {
        string name
    }
    Atlas_Enfermedades {
        string name
    }
    SNIB {
        string name
    }
    Deforestacion {
        string nombre_entidad "Nombre de la entidad federativa"

        string nombre_municipio "Nombre del municipio"

        string clave_municipio "Clave Geoestadística Integrada (CVEGEO) del INEGI"

        number year "Año de la observación"

        number gain_total_ha "Ganacia total de bosque registrada en 5 años (hectáreas)."

        string loss_ha "Pérdida anual de bosque (hectáreas)."

        string treecover2000_ha "Cobertura forestal en el municipio observada en el 2000"
    }
    Programas_Sociales {
        string Dependencia
    }
    Sembrando_Vida {
        string name
    }

    WorldClim_EN {
        string clave
        string descripcion
    }
    WorldClim_SP {
        string clave
        string descripcion
    }
    Contaminacion_Atmosferica {
        string name
    }
    ENVIREM {
        string name
    }
    Climod {
        string name
    }
    USGS_GTOPO {
        string name
    }
    HYDRO1K {
        string name
    }
    GBIF {
        string name
    }
    WorldCliim_CC {
        string name
    }
    ENSANUT {
        string name
    }

